e_23
SELECT PRODID,PDESC,CATEGORY from Product where lower(CATEGORY)='electronics';

e_24
select PRODID,SUBSTR(PDESC,1,5) as PDESC_FIVE,CATEGORY from Product ;

e_25
SELECT SID as SALE_COUNT
FROM Sale WHERE SLDATE >= DATE_ADD(NOW(),INTERVAL -40 MONTH);
